Dashboard/Models/ErrorViewModel.cs
using System;

namespace Dashboard.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dashboard/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class AddressController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class BusesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/ChildrensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class ChildrensController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class DriversController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/EmergencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class EmergencyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Dashboard.Models;

namespace Dashboard.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dashboard/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class SchoolsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/VouchersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class VouchersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Views/Address/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Buses/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Childrens/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Drivers/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Emergency/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Schools/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Dashboard/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Hafelah";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dashboard</title>
    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/lib/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/lib/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="~/lib/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="~/lib/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="~/lib/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="css/custom.min.css" rel="stylesheet">
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a asp-controller="Home" class="site_title"><span>@ViewData["Title"]</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="/images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>John Doe</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a asp-controller="Home"><i class="fa fa-dashboard"></i> Dashboard </a>
                                </li>
                                <li>
                                    <a asp-controller="Schools"><i class="fa fa-building"></i> Schools </a>
                                </li>
                                <li>
                                    <a asp-controller="Buses"><i class="fa fa-bus"></i> Buses </a>
                                </li>
                                <li>
                                    <a asp-controller="Drivers"><i class="fa fa-users"></i> Drivers </a>
                                </li>
                                <li>
                                    <a asp-controller="Childrens"><i class="fa fa-child"></i> Childrens </a>
                                </li>
                                <li>
                                    <a asp-controller="Vouchers"><i class="fa fa-newspaper-o"></i> Vouchers </a>
                                </li>
                                <li>
                                    <a asp-controller="Emergency"><i class="fa fa-plus-circle"></i> Emergency </a>
                                </li>
                                <li>
                                    <a asp-controller="Address"><i class="fa fa-location-arrow"></i> Address </a>
                                </li>

                            </ul>
                        </div>


                    </div>
                    <!-- /sidebar menu -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/img.jpg" alt="">John Doe
                                </a>
                                <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="javascript:;"> Profile</a>
                                    <a class="dropdown-item" href="javascript:;">
                                        <span class="badge bg-red pull-right">50%</span>
                                        <span>Settings</span>
                                    </a>
                                    <a class="dropdown-item" href="javascript:;">Help</a>
                                    <a class="dropdown-item" href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                                </div>
                            </li>

                            <li role="presentation" class="nav-item dropdown open">
                                <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                </a>
                                <ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">
                                    <li class="nav-item">
                                        <a class="dropdown-item">
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            @RenderBody()

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Hafela -  Admin Template by <a href="http://fuais.com" target="_blank">Future Advanced Internet Solutions</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="~/lib/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/lib/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/lib/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="~/lib/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="~/lib/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="~/lib/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="~/lib/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="~/lib/Flot/jquery.flot.js"></script>
    <script src="~/lib/Flot/jquery.flot.pie.js"></script>
    <script src="~/lib/Flot/jquery.flot.time.js"></script>
    <script src="~/lib/Flot/jquery.flot.stack.js"></script>
    <script src="~/lib/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="~/lib/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="~/lib/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="~/lib/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="~/lib/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="~/lib/jqvmap/dist/jquery.vmap.js"></script>
    <script src="~/lib/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="~/lib/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/lib/moment/min/moment.min.js"></script>
    <script src="~/lib/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="js/custom.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Dashboard/Views/Vouchers/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@